//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        public int ISBN { get; set; }
        public string B_TITLE { get; set; }
        public int B_UNITPRICE { get; set; }
        public int B_YEAR { get; set; }
        public int B_QOH { get; set; }
        public string B_CATEGORY { get; set; }
        public int AID { get; set; }
        public int SID { get; set; }
    
        public virtual AuthorDetail AuthorDetail { get; set; }
    }
}
