//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class clerk
    {
        public int ClerkID { get; set; }
        public string Name { get; set; }
    }
}
